name: mb-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - qutip>=5
  - pytest
  - pytest-cov
  - pytest-xdist
  - coverage
  - sphinx
  - nbsphinx
  - jupyter
  - matplotlib
  - seaborn
  - pip
  - pip:
    - twine
    - recommonmark
    - sphinx_rtd_theme
